@startuml
abstract class Utilitario {
    + {static} CharProximo(atual:char) : char
    + {static} TeclaUpperConsole(msg:string, Control:bool, Shift:bool) : char
    + {static} NDC_TelaSRU(largura:int, altura:int, mousePosition:Ponto4D) : Ponto4D
    + {static} AjudaTeclado() : void
    + {static} Diretivas() : void
}
@enduml
