@startuml
class Retangulo {
    + Retangulo(_paiRef:Objeto, _rotulo:char)
    + Retangulo(_paiRef:Objeto, _rotulo:char, ptoInfEsq:Ponto4D, ptoSupDir:Ponto4D)
    + <<override>> ToString() : string
}
Objeto <|-- Retangulo
@enduml
