@startuml
class Objeto {
    + Rotulo : char <<get>>
    + PrimitivaTamanho : float <<get>> <<set>>
    + Bbox() : BBox
    + TrocaEixoRotacao(eixo:char) : void
    + Objeto(_paiRef:Objeto, _rotulo:char, objetoFilho:Objeto)
    + ObjetoAtualizar() : void
    + Desenhar(matrizGrafo:Transformacao4D, _camera:Camera) : void
    + FilhoAdicionar(filho:Objeto) : void
    + PontosId(id:int) : Ponto4D
    + PontosAdicionar(pto:Ponto4D) : void
    + PontosAlterar(pto:Ponto4D, posicao:int) : void
    + GrafocenaBusca(_rotulo:char) : Objeto
    + GrafocenaBuscaProximo(objetoAtual:Objeto) : Objeto
    + GrafocenaImprimir(idt:String) : void
    + MatrizImprimir() : void
    + MatrizAtribuirIdentidade() : void
    + MatrizTranslacaoXYZ(tx:double, ty:double, tz:double) : void
    + MatrizEscalaXYZ(Sx:double, Sy:double, Sz:double) : void
    + MatrizEscalaXYZBBox(Sx:double, Sy:double, Sz:double) : void
    + MatrizRotacaoEixo(angulo:double) : void
    + MatrizRotacao(angulo:double) : void
    + MatrizRotacaoZBBox(angulo:double) : void
    + OnUnload() : void
}
Objeto --> "PrimitivaTipo" PrimitiveType
Objeto --> "shaderCor" Shader
@enduml
