@startuml
class Ponto {
    + Ponto(paiRef:Objeto, _rotulo:char)
    + Ponto(paiRef:Objeto, _rotulo:char, pto:Ponto4D)
    + Atualizar() : void
    + <<override>> ToString() : string
}
Objeto <|-- Ponto
@enduml
