@startuml
class SrPalito {
    + SrPalito(paiRef:Objeto, _rotulo:char)
    + Atualizar() : void
    + AtualizarPe(peInc:double) : void
    + AtualizarRaio(raioInc:double) : void
    + AtualizarAngulo(anguloInc:double) : void
    + <<override>> ToString() : string
}
Objeto <|-- SrPalito
@enduml
